# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_final' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios_final
  pod 'Firebase'
  pod 'Firebase/Auth'

  target 'ios_finalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
